function document(varargin)

f1=@(x)isemptynumber(x)||(isrealscalar(x)&&x>0);
f2=@(x)(ischar(x)&&isscalar(x))||(isrealvector(x)&&numel(x)==3&&all(x>=0&x<=1));

P=inputParser;
P.addOptional('FontSize',12,f1);
P.addOptional('LineWidth',.72,f1);
P.addOptional('MarkerSize',4.8,f1);
P.addParameter('FontName','',@isstringscalar);
P.addParameter('Interpreter','',@isstringscalar);
P.addParameter('Units','centimeters',@isstringscalar);
P.addParameter('AxesColor','k',f2);
P.addParameter('BackgroundColor','w',f2);
P.addParameter('TextColor','k',f2);
P.parse(varargin{:});
P=P.Results;

if ~isempty(P.FontSize)
	Groot.setdefault('FontSize$',P.FontSize);
	Groot.setdefault('FontSizeMode$','manual');
end

if ~isempty(P.LineWidth)
	Groot.setdefault('LineWidth$',P.LineWidth);
end

if ~isempty(P.MarkerSize)
	Groot.setdefault('MarkerSize$',P.MarkerSize);
	Groot.setdefault('Head.*Length$',P.MarkerSize);
	Groot.setdefault('Head.*Width$',P.MarkerSize);
end

if ~isempty(P.FontName)
	Groot.setdefault('FontName$',P.FontName);
end

if ~isempty(P.Interpreter)
	Groot.setdefault('Interpreter$',P.Interpreter);
end

if ~isempty(P.Units)
	Groot.setdefault(...
		'AxesUnits$',P.Units,...
		'ColorbarUnits$',P.Units,...
		'FigurePaperUnits$',P.Units,...
		'FigureUnits$',P.Units,...
		'LegendUnits$',P.Units,...
		'PolaraxesUnits$',P.Units,...
		'shapeUnits$',P.Units);
end

if ~isempty(P.AxesColor)
	Groot.setdefault(...
		'Axes.Color$',P.AxesColor,...
		'ColorbarColor$',P.AxesColor,...
		'LegendEdgeColor$',P.AxesColor,...
		'PolaraxesRColor$',P.AxesColor,...
		'PolaraxesThetaColor$',P.AxesColor);
end

if ~isempty(P.BackgroundColor)
	Groot.setdefault(...
		'AxesColor$',P.BackgroundColor,...
		'FigureColor$',P.BackgroundColor,...
		'LegendColor$',P.BackgroundColor,...
		'PolaraxesColor$',P.BackgroundColor);
end

if ~isempty(P.TextColor)
	Groot.setdefault(...
		'TextColor$',P.TextColor,...
		'TextboxshapeColor$',P.TextColor);
end

% Fixed settings.
Groot.setdefault(...
	'AxesLayer$','top',...
	'AxesBox$','on',...
	'ColorbarBox$','on',...
	'HorizontalAlignment$','center',...
	'InvertHardcopy$','off',...
	'LegendBox$','on',...
	'MinorTick$','on',...
	'NextPlot$','add',...
	'PolaraxesLayer$','bottom',...
	'Text.*BackgroundColor$','none',...
	'Text.*EdgeColor$','none',...
	'VerticalAlignment$','middle');

end